spring:
  cloud:
    gateway:
      routes:
#        - id: add_request_parameter_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu

        - id: product
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member
          uri: lb://member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware
          uri: lb://ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party
          uri: lb://third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
              - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}





    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


  application:
    name: gateway
