spring:
  cloud:
    gateway:
      routes:
        - id: add_request_parameter_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: product
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
              - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


#        - id: product
#            uri: lb://product
#            predicates:
#              - Path=/api/**
#            filters:
#              - RewritePath=/api/(?<segment>.*),/$\{segment}




    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


  application:
    name: gateway
