spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.56.10:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
    application:
        name: ware
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
mybatis-plus:
    config-locations: classpath*:/mapper/**/*.xml
    global-config:
        db-config:
            id-type: auto
server:
    port: 8081
